
// Generated by Akka gRPC. DO NOT EDIT.
package org.etri.ado.gateway.openai;

import akka.NotUsed;
import akka.Done;
import akka.annotation.*;
import akka.grpc.internal.*;
import akka.grpc.GrpcClientSettings;
import akka.grpc.javadsl.AkkaGrpcClient;
import akka.grpc.javadsl.SingleResponseRequestBuilder;
import akka.grpc.javadsl.StreamResponseRequestBuilder;
import akka.stream.ActorMaterializer;
import akka.stream.Materializer;
import akka.stream.OverflowStrategy;
import akka.stream.javadsl.Flow;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;
import akka.stream.Materializer;

import io.grpc.*;
import io.grpc.stub.*;

import static org.etri.ado.gateway.openai.ADO.Serializers.*;


import java.util.concurrent.CompletionStage;
import scala.concurrent.ExecutionContext;
import scala.compat.java8.FutureConverters;
import scala.concurrent.Future;
import scala.concurrent.Promise;

public abstract class  ADOClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getAgentById(com.google.protobuf.StringValue) if possible.
     */
    
      public SingleResponseRequestBuilder<com.google.protobuf.StringValue, org.etri.ado.gateway.openai.OpenAI.AgentRef> getAgentById()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getAgentOf(org.etri.ado.gateway.openai.OpenAI.Capabilities) if possible.
     */
    
      public SingleResponseRequestBuilder<org.etri.ado.gateway.openai.OpenAI.Capabilities, org.etri.ado.gateway.openai.OpenAI.Agents> getAgentOf()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getObservation(com.google.protobuf.StringValue) if possible.
     */
    
      public SingleResponseRequestBuilder<com.google.protobuf.StringValue, org.etri.ado.gateway.openai.OpenAI.Observation> getObservation()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}