
// Generated by Akka gRPC. DO NOT EDIT.
package org.etri.ado.gateway.openai;

import akka.NotUsed;
import akka.Done;
import akka.annotation.*;
import akka.grpc.internal.*;
import akka.grpc.GrpcClientSettings;
import akka.grpc.javadsl.AkkaGrpcClient;
import akka.grpc.javadsl.SingleResponseRequestBuilder;
import akka.grpc.javadsl.StreamResponseRequestBuilder;
import akka.stream.ActorMaterializer;
import akka.stream.Materializer;
import akka.stream.OverflowStrategy;
import akka.stream.javadsl.Flow;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;
import akka.stream.Materializer;

import io.grpc.*;
import io.grpc.stub.*;

import static org.etri.ado.gateway.openai.Agent.Serializers.*;


import java.util.concurrent.CompletionStage;
import scala.concurrent.ExecutionContext;
import scala.compat.java8.FutureConverters;
import scala.concurrent.Future;
import scala.concurrent.Promise;

public abstract class  AgentClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getId(com.google.protobuf.Empty) if possible.
     */
    
      public SingleResponseRequestBuilder<com.google.protobuf.Empty, com.google.protobuf.StringValue> getId()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer isCapableOf(com.google.protobuf.StringValue) if possible.
     */
    
      public SingleResponseRequestBuilder<com.google.protobuf.StringValue, com.google.protobuf.BoolValue> isCapableOf()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getCapabilities(com.google.protobuf.Empty) if possible.
     */
    
      public SingleResponseRequestBuilder<com.google.protobuf.Empty, org.etri.ado.gateway.openai.OpenAI.Capabilities> getCapabilities()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer setAction(org.etri.ado.gateway.openai.OpenAI.Action) if possible.
     */
    
      public SingleResponseRequestBuilder<org.etri.ado.gateway.openai.OpenAI.Action, com.google.protobuf.Empty> setAction()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}